### ISSUE TITLE
Type `'group-list'` and `block` editing is broken

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-graphql-gateway#212]
## Description

When using a type `'group-list'` field every time a new list item is added or reordered the hole field is destroyed. 

### Steps to reproduce

Add a `group-list` field somewhere in your app
```
           {
              type: 'group-list',
              label: 'test',
              name: 'test',
              fields:  [
                {
                  label: "Label",
                  name: "label",
                  type: "text",
                },
                {
                  label: "Link",
                  name: "link",
                  type: "text",
                },
              ],
            }
```

and then edit and add new items while watching the state.
### Expected result

Should be able to edit without destroying  sate.

### Actual result

Watch this video: https://www.loom.com/share/a305be9b6263435bac71644086746619

**Comment by jeffsee55** [comment]
This is fixed but at the expense of a slightly broken reset button. The reset only works on the _first_ click
