### ISSUE TITLE
"Description" property not used within sidebar

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#217]
## Description

We have an optional "description" property on all fields, but it doesn't seem to be used.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

I would have expected to see the description test above the field in the sidebar

### Actual result

```
     fields: [           
     {              
          type: 'text',             
          label: 'Title',
          name: 'title',              
          description: "Used for SEO"            
      }]
```

The "description" value isn't used.
<img width="324" alt="Screen Shot 2021-05-25 at 9 51 05 AM" src="https://user-images.githubusercontent.com/3323181/119500982-c6735000-bd3e-11eb-96de-305dfc048c4e.png">

### Environment

```text
  "dependencies": {   "next": "10.2.1",    "postcss": "^8.2.15",    "react": "17.0.2",    "react-dom": "17.0.2",    "react-markdown": "^6.0.2",    "react-tinacms-editor": "^0.41.0",    "react-tinacms-inline": "^0.41.0",   "tina-graphql-gateway": "^0.2.11",    "tinacms": "^0.41.0"  },  "devDependencies": {    "tina-graphql-gateway-cli": "^0.2.42"  }
```

**Comment by jeffsee55** [comment]
The `description` field doesn't get populated from the GraphQL field builders, but the value is there in the `defineSchema`. So this ticket is a matter of make sure that's passed all the way through

**Comment by logan-anderson** [comment]
Took a stab at fixing this but couldn’t follow the flow of building the form if someone takes this one on I would love to be a fly on the wall.
