### ISSUE TITLE
CORS Error: "Access-Control-Allow-Origin: not allowed" when branch name contains a slash

### ISSUE THREAD

**Issue by npeham** [tinacms/tina-graphql-gateway#219]
# Problem
If using the tina cloud client I get a CORS Error when trying to edit my site:

![image](https://user-images.githubusercontent.com/29887207/119456701-3b448b00-bd3b-11eb-8bf9-7c2ed705591d.png)

Url: `https://content.tinajs.io/content/<organizationId>/<clientId>`

I am on localhost and I changed the tina cloud settings according to that:
![image](https://user-images.githubusercontent.com/29887207/119456892-662edf00-bd3b-11eb-92c3-358d1f1566c5.png)

What I don't get is that the "currentUser" request to `https://identity.tinajs.io/realm/<organizationId>/<clientId>` is successful:
![image](https://user-images.githubusercontent.com/29887207/119457344-df2e3680-bd3b-11eb-9261-c7a6cf274903.png)

The local client is working as it should.

# My dependencies
```
"dependencies": {
    "@stitches/react": "latest",
    "next": "10.2.2",
    "next-seo": "4.24.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-tinacms-editor": "^0.41.0",
    "react-tinacms-inline": "^0.41.0",
    "styled-components": "^5.3.0",
    "tina-graphql-gateway": "^0.2.11",
    "tinacms": "^0.41.0"
  },
  "devDependencies": {
    "@axe-core/react": "4.2.0",
    "@svgr/webpack": "5.5.0",
    "@types/react": "17.0.6",
    "husky": "6.0.0",
    "lint-staged": "11.0.0",
    "prettier": "2.3.0",
    "tina-graphql-gateway-cli": "^0.2.42",
    "typescript": "4.2.4"
  },
```

Thanks for your help! :raised_hands:

**Comment by logan-anderson** [comment]
Sorry for the issues @Perni1984  and @npeham as a temporary fix you could try changing the branch name to something without a `/` and that should resolve the cors issue. If that does not work you should make sure that the client in `utils/index.ts` is update to look like

```ts
return new Client({
    organizationId: organization,
    clientId,
    branch: "branch-name-without-slash",
    tokenStorage: "LOCAL_STORAGE",
  });
```

**Comment by Perni1984** [comment]
@logan-anderson @DirtyF @jamespohalloran thanks for all your help - we'll give it a shot tonight.

**Comment by jeffsee55** [comment]
Good catch @logan-anderson. The branch name should probably be url encoded and decoded accordingly

**Comment by Enigmatical** [comment]
Piggybacking on @jeffsee55's comment:
URL encode the branch name in the Client; add a PR to `teams-serverless` and URL decode it (might need to sync up with Commercial):
https://github.com/tinacms/teams-serverless

**Comment by jamespohalloran** [comment]
Created a ticket on the teams-serverless end for the decoding https://github.com/tinacms/teams-serverless

**Comment by npeham** [comment]
@logan-anderson @DirtyF @jamespohalloran Thank you all for your help! It was really the "/" in the branch name. Without any "/" its working as it should :tada: :+1:

**Comment by DirtyF** [comment]
Thanks for confirming @npeham, we'll let you know when the issue is fixed.
