### ISSUE TITLE
Add [Husky CLI](https://github.com/typicode/husky) (or something similar)

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-graphql-gateway#223]
## Description

Right now we have [prettier](https://prettier.io/) as a dev dependency but we are not enforcing styles or even have a prettier config. We should have a set of styles (and possibly eslint rules) that we follow and enforce though the use of git hooks. 

We could use husky (a git hook utility to set up formatting code (or anything) on commits ) and prettier to style the code consistently. I personally have no opinions about what styles are use it would just be nice to follow a set of styles.

**Comment by DirtyF** [comment]
Given the tinacms repository does that, we could use the same rules
