### ISSUE TITLE
Don't build schema "on the fly" on Tina Cloud 

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tina-graphql-gateway#239]
## Summary

We're building the schema every time a request comes in from the content API because we haven't had a cache to put it somewhere. This isn't necessary as the schema is in source control already and can only be changed locally. 

- [ ] Store the [`sectionMap`](https://github.com/tinacms/tina-graphql-gateway/blob/main/packages/tina-graphql/src/index.ts#L94) as a `.json` file in Git as well.
- [ ] Skip the schema [build process](https://github.com/tinacms/tina-graphql-gateway/blob/main/packages/tina-graphql/src/index.ts#L92-L94) for the Github route and grab the files from Github (`schema.gql` and `sectionMap.json`)

### Motivation

This should speed up response times on the Tina Cloud and reduce some complexity around it.

**Comment by mitchmac** [comment]
I think there's a side benefit here that Tina Cloud's schema can't accidentally drift from what's intentionally committed by the developer (probably what version they are using locally), so we decrease the chance of mismatches and unexpected, tough to debug issues?

**Comment by jeffsee55** [comment]
@mitchmac I think this would prevent the developer from breaking the _schema_, but then when we resolve the data I think any changes they may have snuck into a template `.yml` file in the `__generated__` folder would cause our resolver logic to break. Still, seems like a developer would have to do that intentionally
