### ISSUE TITLE
Cannot create/delete documents

### ISSUE THREAD

**Issue by npeham** [tinacms/tina-graphql-gateway#251]
## Description

I am currently struggling by creating or deleting documents via the tina-graphql-gateway.

#### First approach: 

https://tina.io/docs/plugins/content-creators/#examples

As the docu states you just have to create your own plugin and then add it to tina. I did this and added it to my sidebar:

1. The Mutation, I looked through the possible graphql apis and the `addPendingDocument` mutation looked most promising:

```
const successStoryMutation = `#graphql
  mutation SuccessStoryMutation($relativePath: String!, $collection: String!, $template: String!) {
    addPendingDocument(relativePath: $relativePath, collection: $collection, template: $template) {
     id
    }
  }
`;
```

2. Create the Plugin, I used hardcoded values, so the fields are not important and just here for demonstration:
```
const SuccessStoryCreatorPlugin: ContentCreatorPlugin<any> = {
  __type: 'content-creator',
  name: 'SuccessStoryCreatorPlugin',
  fields: [
    {
      label: 'Title',
      name: 'title',
      component: 'text',
    },
    {
      label: 'Date',
      name: 'date',
      component: 'date',
      description: 'The default will be today.',
    },
    {
      label: 'Author',
      name: 'author_name',
      component: 'text',
      description: 'Who wrote this, yo?',
    },
  ],
  onSubmit(values, cms) {
    const client = createClient();

    client
      .request<Document>(successStoryMutation, {
        variables: {
          relativePath: 'new-story',
          collection: 'successStories',
          template: 'successStory',
        },
      })
      .then(() => {
        console.log('its working');
      })
      .catch(() => {
        console.log('ERROR');
      });
  },
};
```

3. Add the plugin: 
```
const TinaWrapper = (props) => {
  const cms = React.useMemo(() => {
    return new TinaCMS({
      apis: {
        tina: createClient(),
      },
      sidebar: true,
      enabled: true,
      plugins: [SuccessStoryCreatorPlugin],
    });
  }, []);
```

4. Result = the Error:

Request:
![image](https://user-images.githubusercontent.com/29887207/121362680-8fa05b00-c936-11eb-93c3-8ad2310b1703.png)

Error:
```
{
  "errors": [
    {
      "message": "Unable to parse file, unknown extension  for path .tina/__generated__/config/front_matter/templates",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "addPendingDocument"
      ]
    }
  ],
  "data": {
    "addPendingDocument": null
  }
}
```

#### Second approach:
I just tried out this docu: https://tina.io/docs/tina-cloud/client/#usedocumentcreatorplugin

So I used the hook `useDocumentCreatorPlugin` like this without the optional parameters:
```
const TinaWrapper = (props) => {
  useDocumentCreatorPlugin();

  const cms = React.useMemo(() => {
    return new TinaCMS({
      apis: {
        tina: createClient(),
      },
      sidebar: true,
      enabled: true,
      plugins: [],
    });
  }, []);
```

Resulting to this error:
![image](https://user-images.githubusercontent.com/29887207/121363815-8f548f80-c937-11eb-89bf-e8036a4f1fdb.png)

### Expected result

The new page with the provided relativePath, collection, template should be created without errors.

### Actual result

Errors I mentioned above.

### Environment
```
 "dependencies": {
    "@stitches/react": "latest",
    "gatsby-tinacms-remark": "^0.41.0",
    "next": "10.2.3",
    "next-seo": "4.24.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-tinacms-editor": "^0.41.0",
    "react-tinacms-inline": "^0.41.0",
    "styled-components": "^5.3.0",
    "tina-graphql-gateway": "^0.2.11",
    "tinacms": "^0.41.0"
  },
  "devDependencies": {
    "@axe-core/react": "4.2.1",
    "@svgr/webpack": "5.5.0",
    "@types/react": "17.0.9",
    "husky": "6.0.0",
    "lint-staged": "11.0.0",
    "prettier": "2.3.1",
    "tina-graphql-gateway-cli": "^0.2.42",
    "typescript": "4.3.2"
  },
```

| Tool    | Version |
| ------- | ------- |
| browser | Chrome Version 90.0.4430.93        |
| os      |  Ubuntu 18.04       |
| node    |  12.16  |
| npm     |  6.14.4       |
| tinacms | 0.41.0        |

@jeffsee55 Maybe you could help here? Did I overlook a docu?

**Comment by jeffsee55** [comment]
Thanks for the detailed ticket @npeham!

The second approach is our recommended setup for now since it's a bit cumbersome to build your own. But either _should_ work. 

From looking at your example in the first approach, I think all you're missing is the file extension in the `relativePath` field (we also don't support `-` in filenames at the moment):

```js
client
      .request<Document>(successStoryMutation, {
        variables: {
          relativePath: 'new-story', // this should be `newStory.md`
          collection: 'successStories',
          template: 'successStory',
        },
      })
```

For the second approach, I think it's just using the `useDocumentCreatorPlugin` hook too soon, we're not setting up the Tina CMS context until the next line:
```js
const TinaWrapper = (props) => {
  useDocumentCreatorPlugin(); // cms doesn't exist yet

  const cms = React.useMemo(() => {
    return new TinaCMS({
      apis: {
        tina: createClient(),
      },
      sidebar: true,
      enabled: true,
      plugins: [],
    });
  }, []);

  return <TinaCloudAuthWall cms={cms}>{children}</TinaCloudAuthWall>;
```
So you can use `useDocumentCreatorPlugin()` inside the `children` of this example

**Comment by npeham** [comment]
@jeffsee55 Thank you very much for your fast reply!

I proceeded now with the first approach and it works now :tada: 

I will try the second approach (=hook) too and will let you know if it is working for me too.

When do you plan to implement deleting documents?

**Comment by npeham** [comment]
@jeffsee55 Just tried it and it works beautiful with the hook approach: 

![image](https://user-images.githubusercontent.com/29887207/121388661-f1b78b00-c94b-11eb-856e-399713cc5f24.png)

Thank you! :pray: 

Issue can can be /closed

**Comment by DirtyF** [comment]
> tina_cms_for_the_win

😄
