### ISSUE TITLE
Unable to query template with Select type

### ISSUE THREAD

**Issue by ACoolTurtle** [tinacms/tina-graphql-gateway#271]
## Description

Graph API unable to interpret Select component, gives the following error when queried: 

```
String cannot represent value: { label: "foo", value: "foo" }
String cannot represent value: { label: "bar", value: "bar" }
```

### Steps to reproduce

Create a schema including options

```
defineSchema({
	collections: [
		{
			label: "A Cool Collection",
			name: "collection",
			path: "foo/bar",
			templates: [
				{
					label: "Template",
					name: "template",
					fields: [
						{
							type: "select",
							label: "Select Element",
							name: "select",
							options: ["foo", "bar"],
						},
					],
				},
			],
		},
     ]
 });
```

### Expected result

The query to not error.

### Actual result

```
String cannot represent value: { label: "foo", value: "foo" }
String cannot represent value: { label: "bar", value: "bar" }
```

#### Tinacms Package Versions

```
react-tinacms-editor@npm:0.41.1
react-tinacms-inline@npm:0.41.1
tinacms@npm:0.41.1
```

#### Tools

| Tool    | Version |
| ------- | ------- |
| browser |  Chrome 91.0.4472.106       |
| os      |     Windows 10, WSL 2 Ubuntu |
| node    |        15.7.0 |
| npm     |       7.4.3  |

**Comment by ACoolTurtle** [comment]
Upon further review, this error is directly related to the `options` child of the `form` request to the Tina API. This error does not appear locally, which makes me think that the API version may be outdated at the moment.

**Comment by jeffsee55** [comment]
Thanks @ACoolTurtle , I think you're right - we need to bump the version on the cloud server

**Comment by ACoolTurtle** [comment]
Ok, sounds good! Has there been any progress on this?

**Comment by DirtyF** [comment]
@ACoolTurtle We'll update the issue when we have progress to share, stay tuned!

**Comment by jamespohalloran** [comment]
That's now been updated to the latest version in Tina Cloud server!

**Comment by ACoolTurtle** [comment]
This bug seems to have worked its way back into this package. I have not found the commit where it was re-added yet, however when running local on the latest version, and querying a Select field, you once again receive the error `String cannot represent value:`. When requesting from the Tina server, the only response now is `Something went wrong.`

**Comment by logan-anderson** [comment]
@ACoolTurtle Thanks for brining this to our attention. Here is a related issue: https://github.com/tinacms/tina-graphql-gateway/issues/296

**Comment by logan-anderson** [comment]
@ACoolTurtle this should be fixed by https://github.com/tinacms/tina-graphql-gateway/pull/304/files

**Comment by ACoolTurtle** [comment]
@logan-anderson this issue was fixed, however #296 still seems to be in effect from my side. However, this issue has been rectified. Thank you!

**Comment by logan-anderson** [comment]
@ACoolTurtle you are correct, thanks for pointing this out. There may have been an issue with the way we published the package.

**Comment by logan-anderson** [comment]
@ACoolTurtle #296 is fixed now. The fix can be applied by running `yarn add tina-graphql-gateway-cli --dev`
