### ISSUE TITLE
Tina CLI 1.1

### ISSUE THREAD

**Issue by jeffsee55** [tinacms/tina-graphql-gateway#276]
Tweaks to UX (clearer paths, better styling) to make things more streamlined.

Blocked by https://github.com/tinacms/tina-graphql-gateway/issues/275

**Comment by logan-anderson** [comment]
Scope
> Hello! and thanks for bootstrapping a Tina App! Before you do anything click on the pencil icon in the bottom left hand corner. You can now edit this content in real time! Click save and notice that you have update the Hello world blog post in the local file system

* Make this text stand out more and easier to read (maybe shorter as well)
* Have a basic guide that allows a user to go into edit mode
* pop up "do you want us add these scripts to the package.json for you" ?
* Add two headings one for getting started with Tina Cloud and one for adding edit state to your App.
