### ISSUE TITLE
init command output is a bit verbose

### ISSUE THREAD

**Issue by mitchmac** [tinacms/tina-graphql-gateway#288]
## Description

The init command is a quick way to get Tina added to a Next.js site and learn a bit about what's going on with the various pieces. The first bit of output can contain some cryptic output that makes it a bit difficult to follow:

```
Compiling...

      .tina/schema.ts not found, Creating one for you...
      See Documentation: https://tina.io/docs/tina-cloud/cli/#getting-started"

Transpiling...
Collection 'posts', path 'content/posts' not found, check that path exists on your filesystem
Tina config ======> /Users/mitch/Desktop/dev-2021/demo/.tina/__generated__/config
Done Compiling...
Building schema...
Generating types...
Typescript types => /Users/mitch/Desktop/dev-2021/demo/.tina/__generated__/types.ts
GraphQL types ====> /Users/mitch/Desktop/dev-2021/demo/.tina/__generated__/schema.gql
```

### Steps to reproduce

Run init in a fresh install of a Next.js site.

```
npx create-next-app --example with-typescript demo
cd demo
npx tina-graphql-gateway-cli init
```

### Expected result

The output from the actual init command provides a good flow of context. If we need to output the above information, we could add a bit of context to the logging to explain why and what is going on. For example, what is compiling and transpiling and why is it important?

**Comment by DirtyF** [comment]
A common pattern: default output is non-verbose just stating what has been done at the end, an optional verbose command can be passed to get the full details of what is done.

**Comment by logan-anderson** [comment]
@DirtyF I like that!

@jeffsee55 maybe we should use a logging library to make this easier?

Maybe 
https://www.npmjs.com/package/loglevel
https://www.npmjs.com/package/npmlog

or some more complex ones
https://www.npmjs.com/package/winston
https://www.npmjs.com/package/morgan
https://www.npmjs.com/package/bunyan
