### ISSUE TITLE
Unable to use `list` field

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-graphql-gateway#296]
## Description

When using a list field in my schema i get this error in the terminal.
```
react_devtools_backend.js:2560 Error: Unable to fetch, errors: 
	String cannot represent value: { value: "", label: "" }
    at LocalClient.request (index.js?cda2:309)
```
### Steps to reproduce

1. Clone mono repo
2. Add the following field in a template.
```js
{
              type: 'list',
              label: 'tags',
              name: 'tags',
              field: {
                component: 'text',
              },
},
```
You now are unable to load this page it can not fetch the content (get the error message above).

### Expected result

The list field should work

### Actual result

Cannot load content and get an error.

Tagging @jeffsee55  as this it probably related to https://github.com/tinacms/tina-graphql-gateway/pull/262

**Comment by logan-anderson** [comment]
Note: this also happens with `reference-list`

**Comment by logan-anderson** [comment]
Issue still happening when on the latest version of `tina-graphql-gateway`. I am assuming it Didn't get published with the latest version of `tina-graphql`

**Comment by ACoolTurtle** [comment]
@logan-anderson This error just showed up again on the Cloud API. How are you controlling it's versioning right now?

**Comment by jeffsee55** [comment]
Sorry for the trouble @ACoolTurtle , we're working on versioning but for now it's a bit of a slower process that we need to do manually. The update should be out tomorrow so we'll circle back on this then.

**Comment by logan-anderson** [comment]
@ACoolTurtle @jeffsee55 I just tested this and it looks like it is fixed. Let us know if you run into any more issues
