### ISSUE TITLE
feat: check before adding files though tina init

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-graphql-gateway#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Runtime error when opening http://localhost:3000/demo/blog/HelloWorld on the cloud starter

### Expected Behavior

No error

### Steps To Reproduce

1. run `npx tina-graphql-gateway-cli init` in the cloud starter repository
2. run `yarn dev`
3. open http://localhost:3000/demo/blog/HelloWorld

### Environment

```markdown
- Browser: Firefox 89.x
- OS: MacOS 11.4
- Node: 14.17
- npm: 7.19
```

### Anything else?

<img width="1121" alt="CleanShot 2021-07-05 at 10 51 26@2x" src="https://user-images.githubusercontent.com/103008/124445026-78129180-dd7f-11eb-8005-0421b053185b.png">

**Comment by logan-anderson** [comment]
@DirtyF The `Tina init` command is for adding Tina to an existing next.js starter app. I am assuming it Didn't work on the cloud starter as it already has Tina setup.
