### ISSUE TITLE
bug: tina init on next.js starter

### ISSUE THREAD

**Issue by DirtyF** [tinacms/tina-graphql-gateway#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given I run tina init in default next.js blog starter
When I open the example URL
Then I get an error

https://www.loom.com/share/754187057bc146958d90f31153cc8638

### Expected Behavior

Provide all steps needed to be able to display the example page with no error.

### Steps To Reproduce

1. `yarn create next-app --example blog-starter blog-starter-app`
2. `cd blog starter-app `
3. `npx tina-graphql-gateway-cli init`
4. `yarn dev`

### Environment

```markdown
- Browser: Firefox
- OS: macOS
- Node: 14.17
- npm: 7
```

### Your Schema

```javascript
import { defineSchema } from "tina-graphql-gateway-cli";

export default defineSchema({
  collections: [
    {
      label: "Blog Posts",
      name: "posts",
      path: "content/posts",
      templates: [
        {
          label: "Article",
          name: "article",
          fields: [
            {
              type: "text",
              label: "Title",
              name: "title",
            },
          ],
        },
      ],
    },
  ],
});
```

### Your GraphQL Query

```graphql
query BlogPostQuery($relativePath: String!) {
    getPostsDocument(relativePath: $relativePath) {
      data {
        __typename
        ... on  Article_Doc_Data{
          title
          _body
        }
      }
    }
  }
```

### Anything else?

The default output doesn't say anything about the need to create an account on Tina, provide an env file, etc.

**Comment by logan-anderson** [comment]
This is probably an issue with the dev command.
@DirtyF 
I am guessing your package.json build script looks like this
```
"dev": "yarn tina-gql server:start -c \"next\"",
```
I am pretty sure our server assumes 2 parts to the command so it needs to be something like this
```
"dev": "yarn tina-gql server:start -c \"next dev\"",
```

**Comment by logan-anderson** [comment]
@DirtyF  this is fixed by https://github.com/tinacms/tina-graphql-gateway/pull/320

**Comment by logan-anderson** [comment]
> The default output doesn't say anything about the need to create an account on Tina, provide an env file, etc.

@DirtyF  This information is provided in the `HellloWorld` Page
