### ISSUE TITLE
tina-graphql-gateway release

### ISSUE THREAD

**Issue by mittonface** [tinacms/tina-graphql-gateway#339]
Whenever we release to beta we will need to also have a version of `tina-graphql-gateway` that points the the appropriate endpoints.

These are captured in https://github.com/tinacms/tina-graphql-gateway/pull/285 and for right now we're just testing them out in dev releases. 

At some point we will need to do a full release, this will be a breaking change.

**Comment by jeffsee55** [comment]
@mittonface would it make sense for https://github.com/tinacms/tina-graphql-gateway/pull/285/files to work with either old or new configs? I could take a stab at that, and if `organizationId` is not provided, assume the new API is what we're after?

**Comment by logan-anderson** [comment]
@jamespohalloran can this be closed?

**Comment by jamespohalloran** [comment]
Yup!
