### ISSUE TITLE
bug: Can not save .json files with with `unstable_defineSchema` 

### ISSUE THREAD

**Issue by logan-anderson** [tinacms/tina-graphql-gateway#347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When using `unstable_defineSchema` and --experimental flag in the CLI I am unable to save json documents.

### Expected Behavior

Should be able to save document

### Steps To Reproduce

1. In experimental starter in the mono repo add this to the schema.ts  collections (may also have to update tinacms dep to 0.43.0)
```
{
      label: 'test',
      name: 'test',
      path: 'content/test',
      format: 'json',
      fields: [
        {
          label: 'test',
          name: 'test',
          type: 'string',
        },
      ],
    },
```

Add a test.json with some dummy data
and add this query to your pages/index.tsx file
```
getTestDocument(relativePath: "test.json") {
      data {
        test
      }
    }
```

Edit some data and when you click save you get the following error in the network request
```
{"errors":[{"message":"Expected to find field by name 0","locations":[{"line":3,"column":3}],"path":["updateTestDocument"]}],"data":null}
```

### Environment

```markdown
- Browser:
- OS: 
- Node: 
- npm:
```

### Your Schema

```javascript
na
```

### Your GraphQL Query

```graphql
na
```

**Comment by jeffsee55** [comment]
What was the result of the `test.json` file? Does it have data in it?

**Comment by jeffsee55** [comment]
Just reopening this because I'm not 100% it's fixed. I ran into a separate error message when I tried working with JSON

**Comment by logan-anderson** [comment]
I tried both with and without data. Same error message.

**Comment by jeffsee55** [comment]
Ah got it reproduced. This is a bug when the collection name is the same as the field name, so I think it'd happen with markdown too

**Comment by logan-anderson** [comment]
@jeffsee55 is this fixed now?
