### ISSUE TITLE
Add support for Include field

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#43]
Eventually, we would like to be able to define [include fields](https://forestry.io/docs/settings/fields/include-template/) in our templates. 

It will need to be added here: https://github.com/forestryio/graphql-demo/blob/master/packages/graphql/src/fields/index.ts

**Comment by jeffsee55** [comment]
We'll likely handle this with a one-time migration which just copies your included fields into the respective template definitions
