### ISSUE TITLE
schema:migrate fails with empty fields array in template

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#46]
I have an empty template:
```
---
label: gallery
hide_body: true
fields: []
```
When I run: `yarn tina-gql schema:migrate`, I get:

> gallery.yml is invalid. should have required property 'fields'

The "fields" property is present, but it's empty. I'd expect this to be valid

**Comment by jeffsee55** [comment]
Now that we're using `.ts` for configs, this migration will need to be a one-time thing we have yet to build
