### ISSUE TITLE
new_doc_ext in settings.yml doesn't accept "json" as value 

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#47]
When I try and run `yarn tina-gql schema:migrate` on my site

I get: 
```
.sections[0].new_doc_ext should be equal to one of the allowed values but got string (json)
        Allowed values: md, html
```

I don't think we allow creating Html files in Forestry, do we?

**Comment by jeffsee55** [comment]
Now that we're using `.ts` for configs, this migration will need to be a one-time thing we have yet to build
