### ISSUE TITLE
Need error message when no templates defined on section

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#48]
When you run: `yarn tina-gql schema:gen-query --typescript` on a site that contains a section with no templates field defined, you get an error like:

```
  Syntax Error: Unexpected Name "Mutation".

GraphQL request:7:6
6 |
7 | type Mutation {
  |      ^
8 |   updateDocument(path: String!, params: DocumentInput): DocumentUnion
```

It would be good to catch this, and display an error message.

**Comment by jeffsee55** [comment]
Now that we're using `.ts` for configs, this migration will need to be a one-time thing we have yet to build
