### ISSUE TITLE
leading slash in FMT's "pages" list must match graphql server's "path" value exactly

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina-graphql-gateway#50]
If my FMT's "pages" property is defined as:
```
pages:
  - content/main.md
```
then the path property that I send to the graphql server must not contain a leading slash, or else I get:

> Unable to find active template for ...

Vice-versa if my "pages" property contains a leading slash, and the path property doesn't.

Ideally, we could strip the leading slashes consistently to be a bit more forgiving

**Comment by jeffsee55** [comment]
Now that we're using `.ts` for configs, this migration will need to be a one-time thing we have yet to build
